### ISSUE TITLE
Java constructor for "java.lang.InternalError" with arguments "string,string,number" not found.

### ISSUE THREAD

**Issue by fadeli1** [eclipse/birt#1046]
I upgraded birt 4.9.0 from birt 4.3.2

There is a script in fetch that calls a Java method. When the parameter is null, an error occurs. The error message is as follows:
````
A BIRT exception occurred. See next exception for more information.
Java constructor for "java.lang.InternalError" with arguments "string,string,number" not found. (/report/data-sets/script-data-set[@id="11"]/method[@name="fetch"]#46)
        at org.eclipse.birt.data.engine.script.JSMethodRunner.runScript(JSMethodRunner.java:123) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.script.internal.DtEScriptExecutor.handleJS(DtEScriptExecutor.java:88) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.script.internal.DataSetScriptExecutor.handleJS(DataSetScriptExecutor.java:227) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.script.internal.ScriptDataSetScriptExecutor.handleFetch(ScriptDataSetScriptExecutor.java:131) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.ScriptDataSetRuntime.fetch(ScriptDataSetRuntime.java:87) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.PreparedScriptDSQuery$ScriptDSQueryExecutor$CustomDataSet.fetch(PreparedScriptDSQuery.java:234) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.OdiAdapter.fetch(OdiAdapter.java:200) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.fetch(RowResultSet.java:136) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.doNext(RowResultSet.java:119) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.next(RowResultSet.java:98) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.transform.SimpleResultSet$RowResultSetWithResultSetScope.fetch(SimpleResultSet.java:905) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.doNext(RowResultSet.java:119) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.next(RowResultSet.java:98) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.transform.SimpleResultSet.prepareFirstRow(SimpleResultSet.java:257) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.transform.SimpleResultSet.getResultSetIterator(SimpleResultSet.java:272) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.CandidateQuery.execute(CandidateQuery.java:116) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.PreparedScriptDSQuery$ScriptDSQueryExecutor.executeOdiQuery(PreparedScriptDSQuery.java:202) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.QueryExecutor.execute(QueryExecutor.java:1074) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.ServiceForQueryResults.executeQuery(ServiceForQueryResults.java:218) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.QueryResults.getResultIterator(QueryResults.java:170) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.data.dte.QueryResultSet.<init>(QueryResultSet.java:96) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.data.dte.DteDataEngine.doExecuteQuery(DteDataEngine.java:150) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.data.dte.AbstractDataEngine.execute(AbstractDataEngine.java:254) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.executor.ExecutionContext.executeQuery(ExecutionContext.java:1632) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.executor.QueryItemExecutor.executeQuery(QueryItemExecutor.java:73) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.executor.TableItemExecutor.execute(TableItemExecutor.java:60) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.internal.executor.dup.SuppressDuplicateItemExecutor.execute(SuppressDuplicateItemExecutor.java:41) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.internal.executor.wrap.WrappedReportItemExecutor.execute(WrappedReportItemExecutor.java:45) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.internal.executor.l18n.LocalizedReportItemExecutor.execute(LocalizedReportItemExecutor.java:34) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:62) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:97) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:145) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.run(RunAndRenderTask.java:69) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
Caused by: org.eclipse.birt.data.engine.core.DataException: A BIRT exception occurred. See next exception for more information.
Java constructor for "java.lang.InternalError" with arguments "string,string,number" not found. (/report/data-sets/script-data-set[@id="11"]/method[@name="fetch"]#46)
        at org.eclipse.birt.data.engine.core.DataException.wrap(DataException.java:120) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.api.script.BaseScriptEvalUtil.evaluateJSAsExpr(BaseScriptEvalUtil.java:806) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.script.JSMethodRunner.runScript(JSMethodRunner.java:120) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        ... 66 more
Caused by: org.eclipse.birt.core.exception.CoreException: Java constructor for "java.lang.InternalError" with arguments "string,string,number" not found. (/report/data-sets/script-data-set[@id="11"]/method[@name="fetch"]#46)
        at org.eclipse.birt.core.script.JavascriptEvalUtil.wrapRhinoException(JavascriptEvalUtil.java:263) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateRawScript(JavascriptEvalUtil.java:103) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateScript(JavascriptEvalUtil.java:128) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.api.script.BaseScriptEvalUtil.evaluateJSAsExpr(BaseScriptEvalUtil.java:804) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.script.JSMethodRunner.runScript(JSMethodRunner.java:120) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        ... 66 more
Caused by: org.mozilla.javascript.EvaluatorException: Java constructor for "java.lang.InternalError" with arguments "string,string,number" not found. (/report/data-sets/script-data-set[@id="11"]/method[@name="fetch"]#46)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:913) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:969) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:939) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:161) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.Context.newObject(Context.java:1504) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.ScriptRuntime.newCatchScope(ScriptRuntime.java:3290) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__11___method__name__fetch___8145._c___bm_FETCH_1(/report/data-sets/script-data-set[@id="11"]/method[@name="fetch"]:46) ~[?:?]
        at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__11___method__name__fetch___8145.call(/report/data-sets/script-data-set[@id="11"]/method[@name="fetch"]) ~[?:?]
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___10._c_script_0(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"]:0) ~[?:?]
        at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___10.call(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"]) ~[?:?]
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) ~[js-4.9.0-birt.jar:?]
        at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___10.call(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"]) ~[?:?]
        at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___10.exec(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"]) ~[?:?]
        at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateRawScript(JavascriptEvalUtil.java:98) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateScript(JavascriptEvalUtil.java:128) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.api.script.BaseScriptEvalUtil.evaluateJSAsExpr(BaseScriptEvalUtil.java:804) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.script.JSMethodRunner.runScript(JSMethodRunner.java:120) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        ... 66 more
2022-09-16 18:53:54,721 |jsse-nio-8458-exec-4 |ScriptExecutor                |W| Data Set script method "Fetch" returned null; expected a Boolean value.
org.eclipse.birt.report.engine.api.EngineException: Data Set script method "Fetch" returned null; expected a Boolean value.
        at org.eclipse.birt.report.engine.script.internal.ScriptExecutor.addException(ScriptExecutor.java:213) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.script.internal.ScriptExecutor.addException(ScriptExecutor.java:205) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.script.internal.ScriptDataSetScriptExecutor.handleFetch(ScriptDataSetScriptExecutor.java:147) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.ScriptDataSetRuntime.fetch(ScriptDataSetRuntime.java:87) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.PreparedScriptDSQuery$ScriptDSQueryExecutor$CustomDataSet.fetch(PreparedScriptDSQuery.java:234) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.OdiAdapter.fetch(OdiAdapter.java:200) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.fetch(RowResultSet.java:136) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.doNext(RowResultSet.java:119) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.next(RowResultSet.java:98) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.transform.SimpleResultSet$RowResultSetWithResultSetScope.fetch(SimpleResultSet.java:905) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.doNext(RowResultSet.java:119) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.cache.RowResultSet.next(RowResultSet.java:98) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.transform.SimpleResultSet.prepareFirstRow(SimpleResultSet.java:257) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.transform.SimpleResultSet.getResultSetIterator(SimpleResultSet.java:272) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.executor.CandidateQuery.execute(CandidateQuery.java:116) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.PreparedScriptDSQuery$ScriptDSQueryExecutor.executeOdiQuery(PreparedScriptDSQuery.java:202) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.QueryExecutor.execute(QueryExecutor.java:1074) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.ServiceForQueryResults.executeQuery(ServiceForQueryResults.java:218) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.data.engine.impl.QueryResults.getResultIterator(QueryResults.java:170) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.data.dte.QueryResultSet.<init>(QueryResultSet.java:96) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.data.dte.DteDataEngine.doExecuteQuery(DteDataEngine.java:150) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.data.dte.AbstractDataEngine.execute(AbstractDataEngine.java:254) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.executor.ExecutionContext.executeQuery(ExecutionContext.java:1632) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.executor.QueryItemExecutor.executeQuery(QueryItemExecutor.java:73) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.executor.TableItemExecutor.execute(TableItemExecutor.java:60) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.internal.executor.dup.SuppressDuplicateItemExecutor.execute(SuppressDuplicateItemExecutor.java:41) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.internal.executor.wrap.WrappedReportItemExecutor.execute(WrappedReportItemExecutor.java:45) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.internal.executor.l18n.LocalizedReportItemExecutor.execute(LocalizedReportItemExecutor.java:34) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:62) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:97) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:145) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.run(RunAndRenderTask.java:69) [org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
Caused by: org.eclipse.birt.data.engine.core.DataException: Data Set script method "Fetch" returned null; expected a Boolean value.
        at org.eclipse.birt.report.engine.script.internal.ScriptDataSetScriptExecutor.handleFetch(ScriptDataSetScriptExecutor.java:138) ~[org.eclipse.birt.runtime-4.9.0-20220315.jar:?]
        ... 63 more
````
The fetch script code is as follows:
````
UtilMisc.toMap("samplingTypeId", null);
````
My java method is defined as follows:
````
public static <V, V1 extends V> Map<String, V> toMap(String name1, V1 value1) {
         return populateMap(new HashMap<String, V>(), name1, value1);
     }
````
It works fine in birt 4.3.2, but error in brit4.9.0

**Comment by fadeli1** [comment]
I know birt uses rhino library, I did some tests like:
```
public static String test(String abc) {
    	return abc;
 }
public static void main(String[] args) {
    	Context ctx = Context.enter();
    	try {
    		String code = "var test = new Packages.xxx;abc.test(null)";
                Scriptable scope = ctx.initStandardObjects();
                Object result = ctx.evaluateString(scope, code, "<code>", 1, null);
                System.out.println(Context.toString(result));
        } catch(RhinoException ex) {
                System.out.println(ex.getMessage());
        } finally {
                Context.exit();
        }
}
```
After running, it correctly prints null

I use rhino 1.7.14

**Comment by claesrosell** [comment]
Can you confirm that you are running Birt with Java11?
The error message seems strange.

**Comment by hvbtup** [comment]
You said that your `fetch` event looks like this:

    UtilMisc.toMap("samplingTypeId", null);

Of course this is a BIRT bug (the stack trace definitey looks like some internal error), but you should read the stack trace:

    Caused by: org.eclipse.birt.data.engine.core.DataException: Data Set script method "Fetch" returned null; expected a Boolean value.

Your `fetch` event doesn't use `return true;` or `return false;`

The meaning is: "Did we find a record or are we after the last record?"

So in the first place, it is an error in your script.

**Comment by fadeli1** [comment]
@claesrosell 
I use java11 to run and java17 to run

**Comment by fadeli1** [comment]
@hvbtup 
The fetch code is as follows
```
if (countOfRow == totalRow) return false;
...
UtilMisc.toMap("samplingTypeId", null);
...
countOfRow ++;
return true;
```
Strangely, when I change null to a specific character, everything works fine, like
```
UtilMisc.toMap("samplingTypeId", “xxxx”);
```

**Comment by fadeli1** [comment]
Personal guess, when the parameter is null, the reflection method fails

**Comment by fadeli1** [comment]
I also did some other tests like in fecth code:
```
if (countOfRow == totalRow) return false;
...
System.out.println("xxx");
countOfRow ++;
return true;
```
prints xxx

```
if (countOfRow == totalRow) return false;
...
System.out.println(null);
countOfRow ++;
return true;
```
prints xxx
```
error, error message:
```
he choice of Java method java.io.PrintStream.println matching JavaScript argument types (null) is ambiguous; candidate methods are: 
    void println(java.lang.String)
    void println(java.lang.Object)
    void println(char[]) (/report/data-sets/script-data-set[@id="45"]/method[@name="fetch"]#23)
	at org.eclipse.birt.data.engine.script.JSMethodRunner.runScript(JSMethodRunner.java:123)
	at org.eclipse.birt.report.engine.script.internal.DtEScriptExecutor.handleJS(DtEScriptExecutor.java:88)
	... 82 more
Caused by: org.eclipse.birt.data.engine.core.DataException: A BIRT exception occurred. See next exception for more information.
The choice of Java method java.io.PrintStream.println matching JavaScript argument types (null) is ambiguous; candidate methods are: 
    void println(java.lang.String)
    void println(java.lang.Object)
    void println(char[]) (/report/data-sets/script-data-set[@id="45"]/method[@name="fetch"]#23)
	at org.eclipse.birt.data.engine.core.DataException.wrap(DataException.java:120)
	at org.eclipse.birt.data.engine.api.script.BaseScriptEvalUtil.evaluateJSAsExpr(BaseScriptEvalUtil.java:806)
	at org.eclipse.birt.data.engine.script.JSMethodRunner.runScript(JSMethodRunner.java:120)
	... 83 more
Caused by: org.eclipse.birt.core.exception.CoreException: The choice of Java method java.io.PrintStream.println matching JavaScript argument types (null) is ambiguous; candidate methods are: 
    void println(java.lang.String)
    void println(java.lang.Object)
    void println(char[]) (/report/data-sets/script-data-set[@id="45"]/method[@name="fetch"]#23)
	at org.eclipse.birt.core.script.JavascriptEvalUtil.wrapRhinoException(JavascriptEvalUtil.java:263)
	at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateRawScript(JavascriptEvalUtil.java:103)
	at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateScript(JavascriptEvalUtil.java:128)
	at org.eclipse.birt.data.engine.api.script.BaseScriptEvalUtil.evaluateJSAsExpr(BaseScriptEvalUtil.java:804)
	... 84 more
Caused by: org.mozilla.javascript.EvaluatorException: The choice of Java method java.io.PrintStream.println matching JavaScript argument types (null) is ambiguous; candidate methods are: 
    void println(java.lang.String)
    void println(java.lang.Object)
    void println(char[]) (/report/data-sets/script-data-set[@id="45"]/method[@name="fetch"]#23)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:913)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:969)
	at org.mozilla.javascript.Context.reportRuntimeError4(Context.java:956)
	at org.mozilla.javascript.NativeJavaMethod.findFunction(NativeJavaMethod.java:468)
	at org.mozilla.javascript.NativeJavaMethod.findCachedFunction(NativeJavaMethod.java:262)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:139)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__45___method__name__fetch___917._c___bm_FETCH_1(/report/data-sets/script-data-set[@id="45"]/method[@name="fetch"]:23)
	at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__45___method__name__fetch___917.call(/report/data-sets/script-data-set[@id="45"]/method[@name="fetch"])
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
	at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___11._c_script_0(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"]:0)
	at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___11.call(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"])
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___11.call(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"])
	at org.mozilla.javascript.gen._report_data_sets_script_data_set__id__27___method__name__fetch___11.exec(/report/data-sets/script-data-set[@id="27"]/method[@name="fetch"])
	at org.eclipse.birt.core.script.JavascriptEvalUtil.evaluateRawScript(JavascriptEvalUtil.java:98)
	... 86 more
```

**Comment by hvbtup** [comment]
> Personal guess, when the parameter is null, the reflection method fails

Which sounds logical.
I think that Java generics and Rhino cannot work together well.

In Javascript, null ist just null.
It's not a null String, a null Integer, a null (you name it).

I wonder how this could even work with BIRT 4.3.

**Comment by fadeli1** [comment]
I don't know, the script code has not changed, just upgrade BIRT 4.3.2 to 4.9.0.

I subsequently modified the toMap method parameter declaration with no errors.
