### ISSUE TITLE
Unable to start 4.10 Report Designer on Win 10

### ISSUE THREAD

**Issue by GingerJohnny** [eclipse/birt#1095]
I unzipped the "birt-report-designer-all-in-one-4.10.0-20221001-win32.win32.x86_64" and attempted to start the designer by double-clicking on the eclipse.exe which was unpacked from that zip file. I get the following error log. Can someone suggest why? It is my understanding that the JVM is now embedded with the distribution, which seems evident from the ini file line:

-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.4.v20220903-1038/jre/bin

so I am not sure what might be the problem.

John

===========================================

!SESSION 2022-10-26 09:55:26.715 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_351
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.equinox.simpleconfigurator 4 0 2022-10-26 09:55:27.041
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.simpleconfigurator [3]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.osgi 4 0 2022-10-26 09:55:27.042
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.equinox.simpleconfigurator_1.4.100.v20220620-1617.jar was not resolved.

!ENTRY org.eclipse.equinox.simpleconfigurator 2 0 2022-10-26 09:55:27.044
!MESSAGE Could not resolve module: org.eclipse.equinox.simpleconfigurator [3]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

!ENTRY org.eclipse.osgi 4 0 2022-10-26 09:55:27.051
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by speckyspooky** [comment]
I have started the download of your metioned Version from the default download page:
https://download.eclipse.org/birt/downloads/drops/R-R1-4.10.0-202210031241/

I unpacked the all-in-one-designer (birt-report-designer-all-in-one-4.10.0-20221001-win32.win32.x86_64.zip) and started like you the eclipse.exe.
The designer started correctly without any problems on my side.

My birt.ini reference to the same jre like your.

The only point which confused me is your noted jre-version of your ERROR-log because there ist noted "java.version=1.8.0_351".
But the included jre is JAVA_VERSION="17.0.4.1".

This information is located in the "release" file of path "C:\Users\gutma\Downloads\birt-report-designer-all-in-one-4.10.0-20221001-win32.win32.x86_64\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.4.v20220903-1038\jre"

But why reference your error-message to java 1.8...?

**Comment by GingerJohnny** [comment]
Interesting...I found that there was v8 still installed on my PC, even though I have gone through numerous upgrades over the years. You found the problem speckyspooky, as soon as I uninstalled v8, the tool launched successfully.  Many thanks.
