### ISSUE TITLE
Viewer does not work on Linux

### ISSUE THREAD

**Issue by SteveSchafer-Innovent** [eclipse/birt#620]
Jetty component required for viewer is missing.  I tried this in Eclipse 4.14 and 4.19 RC1.  The viewer hasn't worked on Linix since 4.6.  Bugzilla entry: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517662.  The bugzilla entry doesn't explicitly state that it's a Linux issue but that's been my experience.

```
Mar 16, 2021 9:10:10 AM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @70477ms to org.eclipse.jetty.util.log.JavaUtilLog
Mar 16, 2021 9:10:10 AM org.eclipse.jetty.osgi.boot.JettyBootstrapActivator start
WARNING: OSGi support for java.util.ServiceLoader may not be present. You may experience runtime errors.
Mar 16, 2021 9:10:10 AM org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper startJettyAtJettyHome
WARNING: No default jetty created.
Mar 16, 2021 9:10:10 AM org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration configure
WARNING: Config error at <Call name="insertHandler"><Arg>
		  <New id="GzipHandler" class="org.eclipse.jetty.server.handler.gzip.GzipHandler"><Set name="minGzipSize"><Property name="jetty.gzip.minGzipSize" deprecated="gzip.minGzipSize" default="2048"/></Set><Set name="checkGzExists"><Property name="jetty.gzip.checkGzExists" deprecated="gzip.checkGzExists" default="false"/></Set><Set name="compressionLevel"><Property name="jetty.gzip.compressionLevel" deprecated="gzip.compressionLevel" default="-1"/></Set><Set name="syncFlush"><Property name="jetty.gzip.syncFlush" default="false"/></Set><Set name="excludedAgentPatterns">
			  <Array type="String"><Item><Property name="jetty.gzip.excludedUserAgent" deprecated="gzip.excludedUserAgent" default=".*MSIE.6\.0.*"/></Item></Array>
			</Set></New>
		</Arg></Call> java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.gzip.GzipHandler cannot be found by org.eclipse.jetty.osgi.boot_9.4.15.v20190215 in UNKNOWN-LOCATION
Mar 16, 2021 9:10:10 AM org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper configure
WARNING: Configuration error in file:/disk1/home/innovent/.eclipse/org.eclipse.platform_4.14.0_1154590306_linux_gtk_x86_64/plugins/org.eclipse.birt.report.viewer_4.9.0.v202103152015/jettyhome/etc/jetty.xml
Mar 16, 2021 9:10:10 AM org.eclipse.jetty.osgi.boot.internal.serverfactory.JettyServerServiceTracker addingService
WARNING: 
java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.gzip.GzipHandler cannot be found by org.eclipse.jetty.osgi.boot_9.4.15.v20190215
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:514)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:425)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1006)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:942)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:515)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper.configure(ServerInstanceWrapper.java:164)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper.start(ServerInstanceWrapper.java:257)
	at org.eclipse.jetty.osgi.boot.internal.serverfactory.JettyServerServiceTracker.addingService(JettyServerServiceTracker.java:64)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:896)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:834)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:258)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1071)
	at org.eclipse.birt.report.viewer.utilities.ViewerWebServer.start(ViewerWebServer.java:51)
	at org.eclipse.birt.report.viewer.utilities.AppServerWrapper.startJettyServer(AppServerWrapper.java:250)
	at org.eclipse.birt.report.viewer.utilities.AppServerWrapper.start(AppServerWrapper.java:155)
	at org.eclipse.birt.report.viewer.utilities.WebappAccessor.start(WebappAccessor.java:72)
	at org.eclipse.birt.report.viewer.utilities.WebViewer.startWebApp(WebViewer.java:827)
	at org.eclipse.birt.report.viewer.utilities.WebViewer.display(WebViewer.java:1078)
	at org.eclipse.birt.report.viewer.utilities.WebViewer.display(WebViewer.java:1073)
	at org.eclipse.birt.report.designer.ui.actions.PreviewSupport.preview(PreviewSupport.java:402)
	at org.eclipse.birt.report.designer.ui.actions.PreviewSupport$3.widgetSelected(PreviewSupport.java:245)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4935)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4429)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

Opening in existing browser session.
```

**Comment by wimjongman** [comment]
Hey Steve, we are rebooting the project with a new team of committers. Please let us know if you want to help the project out.

Steve, I have created a new build. When I installed BIRT into this build, I could not start the viewer either. However, I could install the all-in-one rcp client and there it worked fine (I have one for windows only ATM).

In order to install from the latest build, use this update site:
https://download.eclipse.org/birt/update-site/4.9/

You can try to install this into a 4.19 but it was built [against 4.11 (2018-12)](https://www.eclipse.org/downloads/packages/release/2018-12/r)

Please try these and report back at your convenience.

**Comment by wimjongman** [comment]
I see the exact same issue in windows. 
[log.txt](https://github.com/eclipse/birt/files/6151720/log.txt)

**Comment by wimjongman** [comment]
This issue is fixed.

Before installing BIRT into 4.19, also add the jetty 9x repo to the list of update sites http://download.eclipse.org/jetty/updates/jetty-bundles-9.x 

https://download.eclipse.org/birt/update-site/4.9/

**Comment by SteveSchafer-Innovent** [comment]
Confirmed the viewer works now once I installed jetty.

**Comment by pipebaum** [comment]
There is a different issue to look at how we handle Jetty. So we have a work around and I want to have a closed issue. :)
Duplicate of #621
