### ISSUE TITLE
Scripted negative margin causes report execution to break for multiple pages

### ISSUE THREAD

**Issue by more-vikr** [eclipse/birt#784]
To reproduce the error you can use the files in the attachment:

- With the first report parameter P_PATH you should point to a directory where the files resist ("/" or "\" at the end!)

P_PATH=`directory with files`

- The second parameter P_GSIZE is intended for switching between small and big header image output.

- P_KOPF conrols the gap on next pages between page top and start of the content.
Further it causes scripted negative margin of -10mm (default) so that the header from the master page will be covered with the report content.

Settings when the report breaks:

P_GSIZE=G
P_CONTENT=I

```
org.eclipse.birt.report.engine.api.EngineException: Error happened while running the report.
	at org.eclipse.birt.report.engine.api.impl.EngineTask.handleFatalExceptions(EngineTask.java:2379)
	at org.eclipse.birt.report.engine.api.impl.RenderTask.render(RenderTask.java:325)
	at more.software.reporting.ExecuteReport.executeReport(ExecuteReport.java:314)
	at more.software.reporting.ExecuteReport.run(ExecuteReport.java:515)
Caused by: java.lang.NullPointerException: Cannot read field "segments" because "border" is null
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.drawBorder(PageDeviceRender.java:1113)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.drawTableBorder(PageDeviceRender.java:1333)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.endContainer(PageDeviceRender.java:591)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:190)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:189)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitChildren(PageDeviceRender.java:200)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.addPage(PageDeviceRender.java:546)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitPage(PageDeviceRender.java:511)
	at org.eclipse.birt.report.engine.layout.emitter.PageDeviceRender.visitContainer(PageDeviceRender.java:184)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ContainerArea.accept(ContainerArea.java:278)
	at org.eclipse.birt.report.engine.layout.emitter.PageEmitter.startPage(PageEmitter.java:51)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.outputPage(LayoutEngine.java:961)
	at org.eclipse.birt.report.engine.nLayout.area.impl.PageArea.outputPage(PageArea.java:707)
	at org.eclipse.birt.report.engine.nLayout.area.impl.PageArea.close(PageArea.java:687)
	at org.eclipse.birt.report.engine.nLayout.area.impl.RootArea.close(RootArea.java:248)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.closeContainer(LayoutEngine.java:374)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine._endContainer(LayoutEngine.java:495)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.endContainer(LayoutEngine.java:359)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterAdapter.endPage(ContentEmitterAdapter.java:70)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.endContent(ContentEmitterUtil.java:102)
	at org.eclipse.birt.report.engine.layout.html.buffer.DummyPageBuffer.endContainer(DummyPageBuffer.java:61)
	at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.end(HTMLPageLM.java:183)
	at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:98)
	at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:100)
	at org.eclipse.birt.report.engine.api.impl.RenderTask$PageRangeRender.render(RenderTask.java:682)
	at org.eclipse.birt.report.engine.api.impl.RenderTask.render(RenderTask.java:321)
	... 2 more
```

[birttest.zip](https://github.com/eclipse/birt/files/7862350/birttest.zip)

**Comment by hvbtup** [comment]
> Further it causes scripted negative margin of -10mm (default) so that the header from the master page will be covered with the report content.

Which BIRT release are you using? I am asking this because we are using the same little trick in some of our reports and it didn't cause problems so far in our reports.

**Comment by hvbtup** [comment]
Your example is not self-contained. The report references a missing library "core" and the data sets do not work (probably developed for an Oracle DB?).
The report references non-existing report parameters (e.g. P_MASSEN).

Please try to create an example that can be tested stand-alone.

**Comment by more-vikr** [comment]
Hello @hvbtup thank you for your answer.

We use the report runtime `org.eclipse.birt.runtime_4.9.0-20190523` for test purposes in the server attached to our ERP system:
The eclipse build info of states:

```
Eclipse Platform
Version: 2021-12 (4.22)
Build id: I20211124-1800
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 17.0.1+12-39
Java version: 17.0.1
```

As I started the designer application today, it executes updates (some of ...2022-03... I think).

Our production system runs on version `org.eclipse.birt.runtime_4.3.2.v20140225-1404` - in this version we are not facing this problem.

I attached a stand-alone version of the test report which is using the Sample DB.
[birttest.zip](https://github.com/eclipse/birt/files/7913034/birttest.zip)
As you can see in `test_preview_eclipse_ok.pdf` the report doesn't break - but the content of the masterpage header is covered.

**Comment by hvbtup** [comment]
I corrected your test report in such a way that it actually works. The P_PATH param must include a trailing backslash (on Windows), otherwise the images are not displayed. 
[birttest.zip](https://github.com/eclipse/birt/files/7914034/birttest.zip)

With a BIRT 4.2.1 All-In-One-Designer the report looks like test_preview_eclipse_ok.pdf.

The lorem ipsum text is truncated between the bottom of page 1 and the top of page 2, but I think this is what is intended.

Then I tested the report from the All-In-One-Designer which I built from the GitHub sources a few days ago.
And I could not reproduce your problem - it does not crash and the report looks the same as with BIRT 4.2.1

You said that you are using org.eclipse.birt.runtime_4.9.0-20190523.
This is quite old - probably the bug has been fixed already.
It might be related to some older bugfix which introduced new problems and which I reverted somewhere after 2019.

So you should try with the current BIRT sources from GitHub.
But be warned, it is not yet perfect, e.g. the POJO runtime doesn't work at the moment.
You can help improving this situation by contributing :-)

As a side note: 
I said that we are using the same trick. But we do it only for the first page.
Like you, we are using
![grafik](https://user-images.githubusercontent.com/7644776/150537640-b92d08d8-dcfc-4ab7-a5c1-706ffa22948c.png)
to hide the header on the first page. In the layout, we are using a negative top-margin for the top-most layout element, which in our case is a separate object that only is displayed once (at the beginning of the layout.

What we don't do is to use a negative margin for layout objects on subsequent pages, and we don't set the margin dynamically in the onCreate event. So we are not exactly in the same situation.

**Comment by hvbtup** [comment]
PLS take a look at the (fixed) issue https://github.com/eclipse/birt/issues/636 - this might be related
